from .gpio import GPIO0, GPIO1, GPIO2, GPIO3, GPIO4
from .pvtm import PVTM_BIGCORE0, PVTM_BIGCORE1, PVTM_LCORE, PVTM_GPU, PVTM_NPU, PVTM_PMU
from .grf import GRF_BIGCORE0, GRF_BIGCORE1, GRF_GPU
from .cru import CRU, CRU_BIGCORE0, CRU_BIGCORE1, CRU_DDR0, CRU_DDR1, CRU_DDR2, CRU_DDR3, CRU_SBUS
from .dmc import DDRCTL_0, DDRCTL_1, DDRCTL_2, DDRCTL_3
from .pmu import PMU
